version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - mvn clean install
      - sed -i 's/\r//' ./deploy-cicd-demo-DEV.sh
      - chmod +x ./deploy-cicd-demo-DEV.sh
      - sh ./deploy-cicd-demo-DEV.sh

artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - sam-cicd-demo-lambdas-packaged.yml
