version: 0.2

phases:
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR
      - mvn clean install
      - cp cicd/* .
      - sed -i 's/\r//' ./package-cicd-demo-DEV.sh
      - chmod +x ./package-cicd-demo-DEV.sh
      - sh ./package-cicd-demo-DEV.sh

artifacts:
  base-directory: $CODEBUILD_SRC_DIR
  files:
    - sam-cicd-demo-lambdas-packaged.yml
    - parameters-DEV.json
    - sam-cicd-demo-apis.yml
  name: CICD-Demo-Build-Artifact
